import Image from 'next/image'
import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

const MODULES=[['Tournament Setup','setup'],['Registration','registration'],['Teams','teams'],['Players','players'],['Groups & Stages','groups-stages'],['Fixtures','fixtures'],['Matches','matches'],['Live Control','live-control'],['Standings','standings'],['Statistics','statistics'],['Awards','awards'],['Officials','officials'],['Venues','venues'],['News','news'],['Sponsors','sponsors'],['Reports','reports']] as const
function label(v:string){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function date(v:string|null){if(!v)return'Not set';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?'Not set':new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric'}).format(d)}

export default async function TournamentWorkspacePage({params}:{params:Promise<{organizationId:string;tournamentId:string}>}){
 const {organizationId,tournamentId}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const {data:membership}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(!membership)notFound()
 const {data:organization}=await supabase.from('organizations').select('id,name,logo_url').eq('id',organizationId).maybeSingle();if(!organization)notFound()
 const {data:tournament}=await supabase.from('tournaments').select('id,name,description,logo_url,cover_url,season_label,start_date,end_date,visibility,status,sports(name)').eq('id',tournamentId).eq('organization_id',organizationId).maybeSingle();if(!tournament)notFound()
 const {data:settings}=await supabase.from('tournament_settings').select('points_for_win,points_for_draw,points_for_loss,allow_draws,extra_time_enabled,penalties_enabled').eq('tournament_id',tournamentId).maybeSingle()
 const {data:counts}=await supabase.from('tournament_module_records').select('module').eq('tournament_id',tournamentId)
 const countMap=(counts??[]).reduce<Record<string,number>>((a,r)=>{a[r.module]=(a[r.module]??0)+1;return a},{})
 const sportRel=tournament.sports as {name:string}|{name:string}[]|null;const sport=Array.isArray(sportRel)?sportRel[0]?.name:sportRel?.name;const base=`/organizations/${organizationId}/tournaments/${tournamentId}`;const canManage=['owner','admin','manager'].includes(membership.role)
 return <div className="min-h-screen bg-[#f2f4f7] text-[#081f49]">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-[74px] max-w-[1450px] items-center gap-4 px-5"><Link href="/dashboard"><Image src="/branding/kulhivaru-full-logo.png" alt="Kulhivaru+" width={150} height={52} priority className="h-auto max-h-[44px] w-auto"/></Link><Link href={`/organizations/${organizationId}/tournaments`} className="ml-auto rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600">← Tournaments</Link></div></header>
  <main className="mx-auto max-w-[1450px] px-5 py-7">
   <section className="overflow-hidden rounded-[28px] bg-[#081f49] text-white shadow-xl">{tournament.cover_url&&<div className="relative h-44"><Image src={tournament.cover_url} alt="" fill className="object-cover opacity-35"/></div>}<div className="p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-2xl bg-white/10">{tournament.logo_url?<Image src={tournament.logo_url} alt="" width={48} height={48} className="h-12 w-12 object-cover"/>:<span className="font-black">{tournament.name.charAt(0).toUpperCase()}</span>}</div><span className="rounded-full bg-amber-50 px-3 py-1 text-[10px] font-extrabold uppercase text-amber-700">{label(tournament.status)}</span><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-extrabold uppercase text-white/70">{sport??'Sport'}</span></div><h1 className="mt-5 text-4xl font-black">{tournament.name}</h1><p className="mt-2 text-sm text-white/60">{tournament.season_label||'No season label'}</p>{tournament.description&&<p className="mt-4 max-w-3xl text-sm leading-6 text-white/70">{tournament.description}</p>}</div>{canManage&&<Link href={`${base}/setup`} className="rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[#081f49]">⚙ Edit Tournament Setup</Link>}</div></div></section>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Sport',sport??'Not available'],['Starts',date(tournament.start_date)],['Ends',date(tournament.end_date)],['Visibility',label(tournament.visibility)]].map(([a,b])=><article key={a} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-slate-400">{a}</p><p className="mt-3 text-lg font-black">{b}</p></article>)}</section>
   <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.85fr]">
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Competition Workspace</p><h2 className="mt-2 text-xl font-black">Tournament modules</h2><p className="mt-2 text-sm text-slate-500">All competition modules are now available. Open any module to manage its records.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{MODULES.map(([name,slug])=><Link key={slug} href={`${base}/${slug}`} className="group flex min-h-[62px] items-center justify-between rounded-xl border-2 border-blue-100 bg-blue-50/40 px-4 transition hover:border-[#0057ff] hover:bg-blue-50"><div><span className="font-bold group-hover:text-[#0057ff]">{name}</span>{slug!=='setup'&&<p className="mt-1 text-[10px] font-bold text-slate-400">{countMap[slug]??0} records</p>}</div><span className="rounded-full bg-[#0057ff] px-3 py-1 text-[10px] font-extrabold uppercase text-white">Open →</span></Link>)}</div></section>
    <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Competition Rules</p><h2 className="mt-2 text-lg font-black">Default settings</h2>{settings?<dl className="mt-5 space-y-4 text-sm">{[['Win points',settings.points_for_win],['Draw points',settings.points_for_draw],['Loss points',settings.points_for_loss],['Draws',settings.allow_draws?'Allowed':'Disabled'],['Extra time',settings.extra_time_enabled?'Enabled':'Disabled'],['Penalties',settings.penalties_enabled?'Enabled':'Disabled']].map(([a,b])=><div key={String(a)} className="flex justify-between gap-4"><dt className="text-slate-500">{a}</dt><dd className="font-black">{String(b)}</dd></div>)}</dl>:<p className="mt-4 text-sm text-slate-500">Settings unavailable.</p>}<Link href={`${base}/setup`} className="mt-6 flex min-h-[44px] items-center justify-center rounded-xl bg-[#0057ff] px-4 text-sm font-extrabold text-white">Edit Rules & Settings</Link></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Access</p><h2 className="mt-2 text-lg font-black">Your tournament access</h2><p className="mt-5 text-sm text-slate-500">Organization role</p><p className="mt-1 font-black">{label(membership.role)}</p></section></div>
   </div>
  </main>
 </div>
}
