import Image from 'next/image'
import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

type Tournament = { id:string; organization_id:string; sport_id:string; name:string; slug:string; description:string|null; logo_url:string|null; cover_url:string|null; season_label:string|null; start_date:string|null; end_date:string|null; registration_opens_at:string|null; registration_closes_at:string|null; timezone:string; visibility:string; status:string; created_at:string; sports:{id:string;name:string;slug:string}|{id:string;name:string;slug:string}[]|null }
type Organization = { id:string; name:string; slug:string; logo_url:string|null }
type Membership = { id:string; role:string; status:string }
type Settings = { tournament_id:string; points_for_win:number; points_for_draw:number; points_for_loss:number; allow_draws:boolean; extra_time_enabled:boolean; penalties_enabled:boolean }

function formatLabel(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,l=>l.toUpperCase())}
function formatDate(value:string|null){if(!value)return 'Not set';const d=new Date(`${value}T00:00:00`);if(Number.isNaN(d.getTime()))return 'Not set';return new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric'}).format(d)}
function getSport(t:Tournament){return Array.isArray(t.sports)?t.sports[0]??null:t.sports}
function statusClasses(s:string){switch(s){case'live':return'bg-red-50 text-red-600 ring-red-100';case'registration':return'bg-cyan-50 text-cyan-700 ring-cyan-100';case'scheduled':return'bg-blue-50 text-[#0057ff] ring-blue-100';case'completed':return'bg-emerald-50 text-emerald-700 ring-emerald-100';case'cancelled':return'bg-red-50 text-red-500 ring-red-100';case'archived':return'bg-slate-100 text-slate-500 ring-slate-200';default:return'bg-amber-50 text-amber-700 ring-amber-100'}}

export default async function TournamentWorkspacePage({params}:{params:Promise<{organizationId:string;tournamentId:string}>}){
 const {organizationId,tournamentId}=await params;const supabase=await createClient();
 const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)redirect('/login');
 const {data:membership,error:membershipError}=await supabase.from('organization_members').select('id, role, status').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(membershipError||!membership)notFound();
 const {data:organization,error:organizationError}=await supabase.from('organizations').select('id, name, slug, logo_url').eq('id',organizationId).maybeSingle();if(organizationError||!organization)notFound();
 const {data:tournament,error:tournamentError}=await supabase.from('tournaments').select(`id,organization_id,sport_id,name,slug,description,logo_url,cover_url,season_label,start_date,end_date,registration_opens_at,registration_closes_at,timezone,visibility,status,created_at,sports(id,name,slug)`).eq('id',tournamentId).eq('organization_id',organizationId).maybeSingle();if(tournamentError||!tournament)notFound();
 const {data:settings}=await supabase.from('tournament_settings').select('tournament_id,points_for_win,points_for_draw,points_for_loss,allow_draws,extra_time_enabled,penalties_enabled').eq('tournament_id',tournamentId).maybeSingle();
 const t=tournament as Tournament,o=organization as Organization,m=membership as Membership,s=settings as Settings|null,sport=getSport(t);const canManage=['owner','admin','manager'].includes(m.role);const initial=o.name.charAt(0).toUpperCase()||'K';const setupUrl=`/organizations/${o.id}/tournaments/${t.id}/setup`;
 const modules=[{name:'Tournament Setup',href:setupUrl,ready:true},...['Registration','Teams','Players','Groups & Stages','Fixtures','Matches','Live Control','Standings','Statistics','Awards','Officials','Venues','News','Sponsors','Reports'].map(name=>({name,href:null,ready:false}))];
 return <div className="min-h-screen bg-[#f2f4f7] text-[#081f49]">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-[74px] max-w-[1450px] items-center gap-4 px-4 sm:px-6 lg:px-8"><Link href="/dashboard"><Image src="/branding/kulhivaru-full-logo.png" alt="Kulhivaru+" width={150} height={52} priority className="h-auto max-h-[44px] w-auto"/></Link><div className="ml-auto"><Link href={`/organizations/${o.id}/tournaments`} className="inline-flex min-h-[42px] items-center rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600">← Tournaments</Link></div></div></header>
  <main className="mx-auto max-w-[1450px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
   <div className="mb-5 flex flex-wrap items-center gap-2 text-xs font-semibold text-slate-400"><Link href="/dashboard">My Kulhivaru</Link><span>/</span><Link href={`/organizations/${o.id}`}>{o.name}</Link><span>/</span><Link href={`/organizations/${o.id}/tournaments`}>Tournaments</Link><span>/</span><span className="text-[#081f49]">{t.name}</span></div>
   <section className="overflow-hidden rounded-[28px] bg-[#081f49] text-white shadow-[0_18px_45px_rgba(8,31,73,0.14)]">{t.cover_url&&<div className="relative h-44 w-full sm:h-56"><Image src={t.cover_url} alt="" fill className="object-cover opacity-45"/></div>}<div className="p-6 sm:p-8"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex flex-wrap items-center gap-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-2xl bg-white/10">{t.logo_url?<Image src={t.logo_url} alt={t.name} width={48} height={48} className="h-12 w-12 object-cover"/>:o.logo_url?<Image src={o.logo_url} alt={o.name} width={48} height={48} className="h-12 w-12 object-cover"/>:<span className="text-lg font-black">{initial}</span>}</div><span className={`rounded-full px-3 py-1 text-[10px] font-extrabold uppercase ring-1 ${statusClasses(t.status)}`}>{formatLabel(t.status)}</span><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-extrabold uppercase text-white/70">{sport?.name??'Sport'}</span></div><h1 className="mt-5 text-3xl font-black sm:text-4xl">{t.name}</h1><p className="mt-2 text-sm text-white/60">{t.season_label||'No season label'}</p>{t.description&&<p className="mt-4 max-w-3xl text-sm leading-6 text-white/70">{t.description}</p>}</div>{canManage&&<Link href={setupUrl} className="rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[#081f49] transition hover:bg-blue-50">⚙ Edit Tournament Setup</Link>}</div></div></section>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Sport',sport?.name??'Not available'],['Starts',formatDate(t.start_date)],['Ends',formatDate(t.end_date)],['Visibility',formatLabel(t.visibility)]].map(([a,b])=><article key={a} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-slate-400">{a}</p><p className="mt-3 text-lg font-black">{b}</p></article>)}</section>
   <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_0.85fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-[#0057ff]">Competition Workspace</p><h2 className="mt-2 text-xl font-black">Tournament modules</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage every part of your competition from this workspace. Available modules are clickable.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{modules.map(item=>item.href?<Link key={item.name} href={item.href} className="group flex min-h-[62px] items-center justify-between rounded-xl border-2 border-blue-100 bg-blue-50/50 px-4 transition hover:border-[#0057ff] hover:bg-blue-50"><span className="font-bold group-hover:text-[#0057ff]">{item.name}</span><span className="rounded-full bg-[#0057ff] px-3 py-1 text-[10px] font-extrabold uppercase text-white">Open →</span></Link>:<div key={item.name} className="flex min-h-[62px] items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-4"><span className="font-bold">{item.name}</span><span className="text-[10px] font-extrabold uppercase text-slate-400">Upcoming</span></div>)}</div></section>
    <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-[#0057ff]">Competition Rules</p><h2 className="mt-2 text-lg font-black">Default settings</h2>{s?<dl className="mt-5 space-y-4 text-sm">{[['Win points',s.points_for_win],['Draw points',s.points_for_draw],['Loss points',s.points_for_loss],['Draws',s.allow_draws?'Allowed':'Disabled'],['Extra time',s.extra_time_enabled?'Enabled':'Disabled'],['Penalties',s.penalties_enabled?'Enabled':'Disabled']].map(([a,b])=><div key={String(a)} className="flex justify-between gap-4"><dt className="text-slate-500">{a}</dt><dd className="font-black">{b}</dd></div>)}</dl>:<p className="mt-4 text-sm text-slate-500">Settings unavailable.</p>}{canManage&&<Link href={setupUrl} className="mt-6 flex min-h-[44px] items-center justify-center rounded-xl bg-[#0057ff] px-4 text-sm font-extrabold text-white hover:bg-[#0049d8]">Edit Rules & Settings</Link>}</section><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-[#0057ff]">Access</p><h2 className="mt-2 text-lg font-black">Your tournament access</h2><p className="mt-5 text-sm text-slate-500">Organization role</p><p className="mt-1 font-black">{formatLabel(m.role)}</p></section></div>
   </div>
  </main>
 </div>
}