import Image from 'next/image'
import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

const MODULE_GROUPS=[
 {title:'Participants',items:[['Registration','registration'],['Teams','teams'],['Players','players'],['Transfers','transfers']]},
 {title:'Competition',items:[['Groups & Stages','groups-stages'],['Fixtures','fixtures'],['Matches','matches'],['Live Control','live-control'],['Standings','standings'],['Statistics','statistics']]},
 {title:'Integrity & Awards',items:[['Discipline','discipline'],['Protests & Appeals','protests-appeals'],['Awards','awards']]},
 {title:'Operations',items:[['Officials','officials'],['Venues','venues'],['Communications','communications'],['Documents','documents']]},
 {title:'Content & Business',items:[['News','news'],['Media','media'],['Sponsors','sponsors'],['Finance','finance'],['Reports','reports']]},
] as const
const SETTINGS=[['Tournament Settings','setup'],['Members & Access','staff-permissions'],['Notifications','notifications'],['Integrations','integrations'],['Activity & Audit Log','activity-audit'],['Archive / Delete','archive-delete']] as const
const label=(v:string)=>v.replaceAll('_',' ').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())
const date=(v:string|null)=>{if(!v)return'Not set';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?'Not set':new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric'}).format(d)}
export default async function TournamentWorkspacePage({params}:{params:Promise<{organizationId:string;tournamentId:string}>}){
 const{organizationId,tournamentId}=await params,supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const{data:membership}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(!membership)notFound();
 const{data:organization}=await supabase.from('organizations').select('id,name,logo_url').eq('id',organizationId).maybeSingle();if(!organization)notFound();
 const{data:tournament}=await supabase.from('tournaments').select('id,name,description,logo_url,cover_url,season_label,start_date,end_date,visibility,status,sports(name)').eq('id',tournamentId).eq('organization_id',organizationId).maybeSingle();if(!tournament)notFound();
 const{data:records}=await supabase.from('tournament_module_records').select('module,status').eq('tournament_id',tournamentId);const all=records??[],countMap=all.reduce<Record<string,number>>((a,r)=>{a[r.module]=(a[r.module]??0)+1;return a},{}),pending=all.filter(r=>['draft','pending'].includes(r.status)).length,completed=all.filter(r=>r.status==='completed').length;
 const sportRel=tournament.sports as {name:string}|{name:string}[]|null,sport=Array.isArray(sportRel)?sportRel[0]?.name:sportRel?.name,base=`/organizations/${organizationId}/tournaments/${tournamentId}`,canManage=['owner','admin','manager'].includes(membership.role);
 const moduleCount=1+MODULE_GROUPS.reduce((n,g)=>n+g.items.length,0);
 return <div className="min-h-screen bg-[#f2f4f7] text-[#081f49]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-[74px] max-w-[1450px] items-center gap-4 px-5"><Link href="/dashboard"><Image src="/branding/kulhivaru-full-logo.png" alt="Kulhivaru+" width={150} height={52} priority className="h-auto max-h-[44px] w-auto"/></Link><span className="hidden text-xs text-slate-400 md:block">/ {organization.name} / Tournament Dashboard</span><Link href={`/organizations/${organizationId}/tournaments`} className="ml-auto rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold">← Tournaments</Link></div></header><main className="mx-auto max-w-[1450px] px-5 py-7">
 <section className="overflow-hidden rounded-[28px] bg-[#081f49] text-white shadow-xl">{tournament.cover_url&&<div className="relative h-40"><Image src={tournament.cover_url} alt="" fill className="object-cover opacity-35"/></div>}<div className="p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-2xl bg-white/10">{tournament.logo_url?<Image src={tournament.logo_url} alt="" width={48} height={48} className="h-12 w-12 object-cover"/>:<span className="font-black">{tournament.name.charAt(0).toUpperCase()}</span>}</div><span className="rounded-full bg-amber-50 px-3 py-1 text-[10px] font-extrabold uppercase text-amber-700">{label(tournament.status)}</span><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-extrabold uppercase text-white/70">{sport??'Sport'}</span></div><h1 className="mt-5 text-4xl font-black">{tournament.name}</h1><p className="mt-2 text-sm text-white/60">{tournament.season_label||'No season label'}</p>{tournament.description&&<p className="mt-4 max-w-3xl text-sm leading-6 text-white/70">{tournament.description}</p>}</div>{canManage&&<Link href={`${base}/setup`} className="rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[#081f49]">⚙ Tournament Settings</Link>}</div></div></section>
 <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Sport',sport??'Not available'],['Starts',date(tournament.start_date)],['Ends',date(tournament.end_date)],['Visibility',label(tournament.visibility)]].map(([a,b])=><article key={a} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-slate-400">{a}</p><p className="mt-3 text-lg font-black">{b}</p></article>)}</section>
 <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Main modules</p><p className="mt-2 text-2xl font-black">{moduleCount}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Operational records</p><p className="mt-2 text-2xl font-black">{all.length}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Needs attention</p><p className="mt-2 text-2xl font-black text-amber-600">{pending}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Completed</p><p className="mt-2 text-2xl font-black text-emerald-600">{completed}</p></article></section>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">24-module organizer workspace</p><h2 className="mt-2 text-xl font-black">Tournament operations</h2><p className="mt-2 text-sm text-slate-500">Run registration, competition, integrity, communications, content, finance and reporting from one workspace.</p><Link href={`${base}/setup`} className="mt-5 flex min-h-[64px] items-center justify-between rounded-xl border-2 border-blue-100 bg-blue-50/40 px-4 hover:border-[#0057ff]"><div><span className="font-bold">Tournament Setup</span><p className="mt-1 text-[10px] font-bold text-slate-400">Core information, dates, registration and match rules</p></div><span className="rounded-full bg-[#0057ff] px-3 py-1 text-[10px] font-extrabold uppercase text-white">Open →</span></Link>{MODULE_GROUPS.map(group=><div key={group.title} className="mt-7"><div className="mb-3 flex items-center gap-3"><h3 className="text-xs font-black uppercase tracking-[.12em] text-slate-400">{group.title}</h3><div className="h-px flex-1 bg-slate-100"/></div><div className="grid gap-3 sm:grid-cols-2">{group.items.map(([name,slug])=><Link key={slug} href={`${base}/${slug}`} className="group flex min-h-[64px] items-center justify-between rounded-xl border-2 border-blue-100 bg-blue-50/40 px-4 hover:border-[#0057ff]"><div><span className="font-bold group-hover:text-[#0057ff]">{name}</span><p className="mt-1 text-[10px] font-bold text-slate-400">{countMap[slug]??0} records</p></div><span className="rounded-full bg-[#0057ff] px-3 py-1 text-[10px] font-extrabold uppercase text-white">Open →</span></Link>)}</div></div>)}</section>
 <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Tournament Dashboard</p><h2 className="mt-2 text-lg font-black">Health & next action</h2><p className="mt-3 text-sm leading-6 text-slate-500">{pending>0?`${pending} record${pending===1?'':'s'} need review or completion.`:'No draft or pending records. Continue the competition workflow.'}</p><div className="mt-5 grid grid-cols-2 gap-3 text-center"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-black">{countMap.teams??0}</p><p className="text-[10px] font-bold text-slate-400">TEAMS</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-black">{countMap.players??0}</p><p className="text-[10px] font-bold text-slate-400">PLAYERS</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-black">{countMap.fixtures??0}</p><p className="text-[10px] font-bold text-slate-400">FIXTURES</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-black">{countMap.matches??0}</p><p className="text-[10px] font-bold text-slate-400">MATCHES</p></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Settings & Administration</p><h2 className="mt-2 text-lg font-black">Tournament controls</h2><div className="mt-4 space-y-2">{SETTINGS.map(([name,slug])=><Link key={slug} href={slug==='setup'?`${base}/setup`:`${base}/${slug}`} className="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold hover:border-blue-200 hover:text-[#0057ff]"><span>{name}</span><span>→</span></Link>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Access</p><p className="mt-3 text-sm text-slate-500">Organization role</p><p className="mt-1 font-black">{label(membership.role)}</p></section></div></div>
 </main></div>}
