'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
const v=(f:FormData,k:string)=>String(f.get(k)??'').trim()
async function auth(f:FormData){const organizationId=v(f,'organization_id'),tournamentId=v(f,'tournament_id');const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const{data:m}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(!m||!['owner','admin','manager'].includes(m.role))redirect(`/organizations/${organizationId}/tournaments/${tournamentId}`);return{supabase,user,organizationId,tournamentId,base:`/organizations/${organizationId}/tournaments/${tournamentId}/registration`}}
export async function saveRegistrationSettings(f:FormData){const a=await auth(f);const status=v(f,'status');const cap=Number(v(f,'team_capacity')||0)||null;const fee=Number(v(f,'registration_fee')||0);const payload={tournament_id:a.tournamentId,status,opens_at:v(f,'opens_at')||null,closes_at:v(f,'closes_at')||null,team_capacity:cap,registration_fee:fee,currency:v(f,'currency')||'MVR',require_payment:f.get('require_payment')==='on',require_documents:f.get('require_documents')==='on',public_instructions:v(f,'public_instructions')||null,confirmation_message:v(f,'confirmation_message')||null,updated_at:new Date().toISOString()};const{error}=await a.supabase.from('tournament_registration_settings').upsert(payload);if(error){console.error(error);redirect(`${a.base}?tab=settings&error=save`)}revalidatePath(a.base);redirect(`${a.base}?tab=settings&saved=1`)}
export async function createManualApplication(f:FormData){const a=await auth(f);const team=v(f,'team_name'),manager=v(f,'manager_name');if(!team||!manager)redirect(`${a.base}?tab=applications&error=required`);const{error}=await a.supabase.from('tournament_registration_applications').insert({tournament_id:a.tournamentId,team_name:team,short_name:v(f,'short_name')||null,manager_name:manager,manager_email:v(f,'manager_email')||null,manager_phone:v(f,'manager_phone')||null,notes:v(f,'notes')||null,status:'submitted',submitted_at:new Date().toISOString(),created_by:a.user.id});if(error){console.error(error);redirect(`${a.base}?tab=applications&error=save`)}revalidatePath(a.base);redirect(`${a.base}?tab=applications&saved=1`)}
export async function updateApplicationStatus(f:FormData){const a=await auth(f);const id=v(f,'application_id'),status=v(f,'status');const allowed=['under_review','changes_requested','approved','waitlisted','rejected'];if(!id||!allowed.includes(status))redirect(`${a.base}?tab=applications&error=invalid`);const{error}=await a.supabase.from('tournament_registration_applications').update({status,decision_notes:v(f,'decision_notes')||null,reviewed_at:new Date().toISOString(),reviewed_by:a.user.id,updated_at:new Date().toISOString()}).eq('id',id).eq('tournament_id',a.tournamentId);if(error){console.error(error);redirect(`${a.base}?tab=applications&error=save`)}revalidatePath(a.base);redirect(`${a.base}?tab=applications&saved=1`)}
export async function updatePaymentStatus(f:FormData){const a=await auth(f);const id=v(f,'application_id'),payment=v(f,'payment_status');if(!['unpaid','pending','paid','waived','refunded'].includes(payment))redirect(`${a.base}?tab=payments&error=invalid`);await a.supabase.from('tournament_registration_applications').update({payment_status:payment,updated_at:new Date().toISOString()}).eq('id',id).eq('tournament_id',a.tournamentId);revalidatePath(a.base);redirect(`${a.base}?tab=payments&saved=1`)}
export async function createInvitation(f:FormData){const a=await auth(f);const team=v(f,'team_name');if(!team)redirect(`${a.base}?tab=invitations&error=required`);const{error}=await a.supabase.from('tournament_registration_invitations').insert({tournament_id:a.tournamentId,team_name:team,contact_name:v(f,'contact_name')||null,email:v(f,'email')||null,phone:v(f,'phone')||null,invited_by:a.user.id});if(error){console.error(error);redirect(`${a.base}?tab=invitations&error=save`)}revalidatePath(a.base);redirect(`${a.base}?tab=invitations&saved=1`)}
