import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

const statuses = ['Draft','Submitted','Under Review','Changes Requested','Approved','Waitlisted','Rejected','Unpaid']

export default async function RegistrationPage({params}:{params:Promise<{organizationId:string;tournamentId:string}>}) {
  const {organizationId,tournamentId}=await params
  const supabase=await createClient()
  const {data:{user}}=await supabase.auth.getUser()
  if(!user) redirect('/login')
  const {data:member}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle()
  if(!member) notFound()
  const {data:tournament}=await supabase.from('tournaments').select('id,name,status,start_date,end_date').eq('id',tournamentId).eq('organization_id',organizationId).maybeSingle()
  if(!tournament) notFound()
  const base=`/organizations/${organizationId}/tournaments/${tournamentId}`
  return <div className="min-h-screen bg-[#f3f6fa] text-[#081f49]">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-16 max-w-[1500px] items-center gap-4 px-5"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#0057ff]">{tournament.name}</p><p className="font-black">Registration</p></div><Link href={base} className="ml-auto rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold">← Workspace</Link></div></header>
    <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6">
      <section className="overflow-hidden rounded-[28px] bg-[#071d45] p-6 text-white sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center"><div className="flex-1"><div className="flex items-center gap-2"><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-black text-emerald-300">REGISTRATION SETUP</span><span className="text-xs text-white/50">Organizer dashboard</span></div><h1 className="mt-4 text-3xl font-black sm:text-4xl">Manage tournament registration</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">Configure registration, review team applications, verify documents and payments, manage invitations, and approve eligible teams from one operational workspace.</p></div><div className="grid grid-cols-2 gap-3"><button className="rounded-xl bg-[#0057ff] px-5 py-3 text-xs font-black">Configure registration</button><button className="rounded-xl bg-white/10 px-5 py-3 text-xs font-black">Preview public form</button><button className="rounded-xl border border-white/15 px-5 py-3 text-xs font-black">Invite team</button><button className="rounded-xl border border-white/15 px-5 py-3 text-xs font-black">Export</button></div></div></section>
      <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Registration status</p><p className="mt-2 text-xl font-black">Not configured</p><p className="mt-1 text-xs text-amber-600">Complete setup to open registration</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Team capacity</p><p className="mt-2 text-xl font-black">0 / —</p><p className="mt-1 text-xs text-slate-400">No capacity configured</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Pending review</p><p className="mt-2 text-xl font-black">0</p><p className="mt-1 text-xs text-slate-400">Applications requiring attention</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-400">Available places</p><p className="mt-2 text-xl font-black">—</p><p className="mt-1 text-xs text-slate-400">Set team capacity first</p></div></section>
      <nav className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2">{['Overview','Applications','Registration Form','Settings','Payments','Invitations'].map((x,i)=><button key={x} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-black ${i===0?'bg-[#081f49] text-white':'text-slate-500 hover:bg-slate-50'}`}>{x}</button>)}</nav>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.75fr]">
        <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#0057ff]">Application pipeline</p><h2 className="mt-1 text-xl font-black">Registration statistics</h2></div><span className="text-xs font-bold text-slate-400">Live operational view</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{statuses.map(x=><button key={x} className="rounded-2xl border border-slate-200 p-4 text-left transition hover:border-blue-300 hover:bg-blue-50/40"><p className="text-2xl font-black">0</p><p className="mt-1 text-xs font-bold text-slate-500">{x}</p></button>)}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#0057ff]">Applications</p><h2 className="mt-1 text-xl font-black">Recent applications</h2></div><div className="ml-auto flex gap-2"><input placeholder="Search team or manager…" className="w-48 rounded-xl border border-slate-200 px-3 py-2 text-xs"/><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Filters</button></div></div><div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-xl">◎</div><p className="mt-4 font-black">No applications yet</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Applications will appear here after registration is opened and teams begin submitting their details.</p><button className="mt-5 rounded-xl bg-[#0057ff] px-5 py-3 text-xs font-black text-white">Create manual application</button></div></section></div>
        <aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#0057ff]">Setup progress</p><h2 className="mt-1 text-xl font-black">Registration checklist</h2><div className="mt-5 space-y-3">{['Registration dates configured','Team capacity configured','Registration form created','Required documents configured','Registration rules published','Confirmation message configured','Registration opened'].map(x=><div key={x} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="h-5 w-5 rounded-full border-2 border-slate-300"/><span className="text-xs font-bold text-slate-600">{x}</span></div>)}</div><button className="mt-5 w-full rounded-xl bg-[#081f49] px-4 py-3 text-xs font-black text-white">Continue setup</button></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#0057ff]">Public registration</p><h2 className="mt-1 font-black">Registration link</h2><p className="mt-3 text-xs leading-5 text-slate-500">A public registration URL and QR code will become available when registration setup is complete.</p><div className="mt-4 grid grid-cols-2 gap-2"><button className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold">Copy link</button><button className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold">QR code</button></div></section></aside>
      </div>
    </main>
  </div>
}
