import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createModuleRecordAction, deleteModuleRecordAction, updateModuleRecordAction } from './actions'

const MODULES = {
  registration:{title:'Registration',singular:'Registration',description:'Manage applications, approvals, eligibility, fees and registration workflow.',fields:['Applicant / team','Contact / category']},
  teams:{title:'Teams',singular:'Team',description:'Manage participating teams, clubs, seeding and tournament status.',fields:['Team name','Club / short name']},
  players:{title:'Players',singular:'Player',description:'Manage rosters, eligibility, shirt numbers and player status.',fields:['Player name','Team / shirt number']},
  'groups-stages':{title:'Groups & Stages',singular:'Stage',description:'Build league, group, knockout and hybrid competition structures.',fields:['Stage / group name','Format / round']},
  draw:{title:'Draw',singular:'Draw item',description:'Manage pots, seeds, draw results and confirmed competition placement.',fields:['Draw item / team','Pot / seed / group']},
  fixtures:{title:'Fixtures',singular:'Fixture',description:'Schedule fixtures with date, venue, round and matchup references.',fields:['Fixture / matchup','Venue / round']},
  matches:{title:'Matches',singular:'Match',description:'Manage match preparation, check-in, lineups, results and confirmation.',fields:['Match / matchup','Venue / round']},
  'live-control':{title:'Live Control',singular:'Live event',description:'Operate periods, clock, score, substitutions, cards, incidents and live notes.',fields:['Event / control item','Match / minute']},
  standings:{title:'Standings',singular:'Standing snapshot',description:'Review ranking snapshots derived from confirmed match results and competition rules.',fields:['Team / ranking entry','Group / position']},
  statistics:{title:'Statistics',singular:'Statistic',description:'Manage tournament, team, player and match performance statistics.',fields:['Statistic name','Player / team']},
  qualification:{title:'Qualification',singular:'Qualification',description:'Manage advancement, knockout progression, third-place rules and qualification status.',fields:['Team / qualifier','Rule / destination']},
  discipline:{title:'Discipline',singular:'Disciplinary case',description:'Manage cards, suspensions, cases, evidence, hearings, decisions, protests and appeals.',fields:['Case / person','Type / sanction']},
  awards:{title:'Awards',singular:'Award',description:'Manage trophies, individual awards, winners and award status.',fields:['Award name','Winner / category']},
  officials:{title:'Officials',singular:'Official',description:'Manage referees, officials, assignments, availability and qualifications.',fields:['Official name','Role / qualification']},
  venues:{title:'Venues',singular:'Venue',description:'Manage grounds, courts, locations, capacities and availability.',fields:['Venue name','Location / capacity']},
  finance:{title:'Finance',singular:'Finance item',description:'Manage budgets, income, expenses, payments, transfers, refunds, receipts and reconciliation.',fields:['Transaction / account','Category / reference']},
  'tasks-readiness':{title:'Tasks & Readiness',singular:'Task',description:'Track operational tasks, owners, deadlines, blockers and tournament readiness.',fields:['Task / checklist item','Owner / area']},
  documents:{title:'Documents',singular:'Document',description:'Track regulations, forms, evidence, approvals and tournament documents.',fields:['Document title','Type / reference']},
  news:{title:'News & Announcements',singular:'News item',description:'Create tournament announcements, updates and publication workflow.',fields:['Headline','Category / summary']},
  sponsors:{title:'Sponsors',singular:'Sponsor',description:'Manage tournament partners, sponsor packages and activation status.',fields:['Sponsor name','Package / contact']},
  'staff-permissions':{title:'Staff & Permissions',singular:'Staff assignment',description:'Track tournament staff, operational roles, access assignments and responsibilities.',fields:['Staff / role','Scope / responsibility']},
  'activity-audit':{title:'Activity & Audit',singular:'Activity item',description:'Track important operational actions, review items and audit references.',fields:['Activity / action','Actor / area']},
  reports:{title:'Reports',singular:'Report',description:'Create operational, competition, disciplinary, finance and management reports.',fields:['Report title','Report type / period']},
  'completion-archive':{title:'Completion & Archive',singular:'Completion item',description:'Manage final review, champion confirmation, awards, final reports and archive readiness.',fields:['Completion item','Owner / result']},
} as const

type ModuleKey = keyof typeof MODULES
type RecordRow={id:string;title:string;subtitle:string|null;status:string;scheduled_at:string|null;created_at:string;data:Record<string,unknown>}
function label(v:string){return v.replaceAll('-',' ').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function localDateTime(v:string|null){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}

export default async function ModulePage({params,searchParams}:{params:Promise<{organizationId:string;tournamentId:string;module:string}>;searchParams:Promise<{saved?:string;deleted?:string;error?:string}>}){
 const {organizationId,tournamentId,module}=await params;const query=await searchParams;if(!(module in MODULES))notFound();const config=MODULES[module as ModuleKey];const supabase=await createClient()
 const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const {data:membership}=await supabase.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(!membership)notFound()
 const {data:tournament}=await supabase.from('tournaments').select('id,name,status').eq('id',tournamentId).eq('organization_id',organizationId).maybeSingle();if(!tournament)notFound()
 const {data:records,error}=await supabase.from('tournament_module_records').select('id,title,subtitle,status,scheduled_at,created_at,data').eq('tournament_id',tournamentId).eq('module',module).order('sort_order').order('created_at',{ascending:false})
 const canManage=['owner','admin','manager'].includes(membership.role);const rows=(records??[]) as RecordRow[];const base=`/organizations/${organizationId}/tournaments/${tournamentId}`
 return <div className="min-h-screen bg-[#f2f4f7] text-[#081f49]">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-[72px] max-w-[1400px] items-center gap-4 px-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#0057ff]">{tournament.name}</p><p className="mt-1 font-black">{config.title}</p></div><Link href={base} className="ml-auto rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600">← Workspace</Link></div></header>
  <main className="mx-auto max-w-[1400px] px-5 py-7">
   <section className="rounded-[28px] bg-[#081f49] p-7 text-white"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-blue-300">Tournament operations</p><h1 className="mt-2 text-3xl font-black">{config.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-white/65">{config.description}</p><div className="mt-5 flex gap-3"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{rows.length} records</span><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{label(tournament.status)}</span></div></section>
   {query.saved==='1'&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">Saved successfully.</div>}{query.deleted==='1'&&<div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-blue-700">Record deleted.</div>}{(query.error||error)&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">The operation could not be completed. Check the fields and try again.</div>}
   <div className="mt-6 grid gap-6 xl:grid-cols-[.75fr_1.25fr]">
    {canManage&&<section className="h-fit rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">Add {config.singular}</p><h2 className="mt-2 text-xl font-black">New record</h2><form action={createModuleRecordAction} className="mt-5 space-y-4"><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="tournament_id" value={tournamentId}/><input type="hidden" name="module" value={module}/><label className="block text-xs font-bold text-slate-500">{config.fields[0]}<input name="title" required maxLength={180} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label><label className="block text-xs font-bold text-slate-500">{config.fields[1]}<input name="subtitle" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold text-slate-500">Status<select name="status" defaultValue="active" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm">{['draft','active','pending','approved','scheduled','live','completed','cancelled','archived'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="block text-xs font-bold text-slate-500">Date / time<input name="scheduled_at" type="datetime-local" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label></div><label className="block text-xs font-bold text-slate-500">Details<textarea name="details" rows={3} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label><label className="block text-xs font-bold text-slate-500">Reference / identifier<input name="reference" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label><label className="block text-xs font-bold text-slate-500">Score / value<input name="score" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label><label className="block text-xs font-bold text-slate-500">Notes<textarea name="notes" rows={2} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></label><button className="w-full rounded-xl bg-[#0057ff] px-5 py-3 text-sm font-extrabold text-white">Add {config.singular}</button></form></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[#0057ff]">{config.title}</p><h2 className="mt-2 text-xl font-black">Manage records</h2></div><span className="text-xs font-bold text-slate-400">{rows.length} total</span></div>{rows.length===0?<div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><p className="font-black">No {config.title.toLowerCase()} records yet</p><p className="mt-2 text-sm text-slate-500">Add the first record using the form.</p></div>:<div className="mt-6 space-y-4">{rows.map(row=><article key={row.id} className="rounded-2xl border border-slate-200 p-5"><form action={updateModuleRecordAction} className="grid gap-3 lg:grid-cols-[1fr_1fr_150px_190px_auto]"><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="tournament_id" value={tournamentId}/><input type="hidden" name="module" value={module}/><input type="hidden" name="id" value={row.id}/><input name="title" defaultValue={row.title} required className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-bold"/><input name="subtitle" defaultValue={row.subtitle??''} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/><select name="status" defaultValue={row.status} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{['draft','active','pending','approved','scheduled','live','completed','cancelled','archived'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select><input name="scheduled_at" type="datetime-local" defaultValue={localDateTime(row.scheduled_at)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/>{canManage&&<button className="rounded-xl bg-[#081f49] px-4 py-2.5 text-xs font-extrabold text-white">Save</button>}</form><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-slate-400">Created {new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(row.created_at))}</div>{canManage&&<form action={deleteModuleRecordAction}><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="tournament_id" value={tournamentId}/><input type="hidden" name="module" value={module}/><input type="hidden" name="id" value={row.id}/><button className="text-xs font-extrabold text-red-500">Delete</button></form>}</div></article>)}</div>}</section>
   </div>
  </main>
 </div>
}
