import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { updateTournamentSetupAction } from './actions'

type Props={params:Promise<{organizationId:string;tournamentId:string}>;searchParams:Promise<{error?:string;saved?:string}>}
type Rules={competition_format?:string;team_registration_enabled?:boolean;player_registration_enabled?:boolean;require_registration_approval?:boolean;allow_roster_changes?:boolean;roster_lock_at?:string|null;yellow_card_suspension?:number|null;red_card_suspension?:number|null;notes?:string}
const input='mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-[#081f49] outline-none transition focus:border-[#0057ff] focus:ring-4 focus:ring-blue-50'
const label='text-xs font-extrabold uppercase tracking-[0.08em] text-slate-500'
const card='rounded-3xl border border-slate-200 bg-white p-6 shadow-sm'
function localDateTime(value:string|null){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const p=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function errorMessage(code?:string){const m:Record<string,string>={'invalid-name':'Enter a valid tournament name.','invalid-dates':'End date cannot be before the start date.','invalid-registration-dates':'Registration closing time cannot be before opening time.','invalid-visibility':'Select a valid visibility.','invalid-status':'Select a valid tournament status.','invalid-rules':'Check the competition rule values and ranges.','invalid-tiebreakers':'Select at least one standings tie-breaker.','save-failed':'The tournament setup could not be saved. Please try again.'};return code?m[code]??'Something went wrong.':null}
function Toggle({name,title,description,checked}:{name:string;title:string;description:string;checked:boolean}){return <label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><input type="checkbox" name={name} defaultChecked={checked} className="mt-0.5 h-5 w-5 accent-[#0057ff]"/><span><span className="block text-sm font-extrabold text-[#081f49]">{title}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span></span></label>}

export default async function TournamentSetupPage({params,searchParams}:Props){
 const {organizationId,tournamentId}=await params,query=await searchParams,supabase=await createClient()
 const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)redirect('/login')
 const {data:membership}=await supabase.from('organization_members').select('role,status').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(!membership)notFound();if(!['owner','admin','manager'].includes(membership.role))redirect(`/organizations/${organizationId}/tournaments/${tournamentId}`)
 const {data:organization}=await supabase.from('organizations').select('id,name').eq('id',organizationId).maybeSingle();if(!organization)notFound()
 const {data:tournament}=await supabase.from('tournaments').select('id,name,description,season_label,start_date,end_date,registration_opens_at,registration_closes_at,timezone,visibility,status,sports(name)').eq('id',tournamentId).eq('organization_id',organizationId).maybeSingle();if(!tournament)notFound()
 const {data:settings}=await supabase.from('tournament_settings').select('points_for_win,points_for_draw,points_for_loss,allow_draws,extra_time_enabled,penalties_enabled,match_duration_minutes,period_count,squad_min,squad_max,lineup_min,lineup_max,substitutions_max,rules,tie_breakers').eq('tournament_id',tournamentId).maybeSingle()
 const sr=tournament.sports as {name:string}|{name:string}[]|null,sport=Array.isArray(sr)?sr[0]?.name:sr?.name,rules=(settings?.rules??{}) as Rules,tieBreakers=(settings?.tie_breakers??['points','goal_difference','goals_for']) as string[],message=errorMessage(query.error)
 const completion=[Boolean(tournament.name),Boolean(tournament.start_date&&tournament.end_date),Boolean(tournament.registration_opens_at&&tournament.registration_closes_at),Boolean(settings?.match_duration_minutes),Boolean(settings?.squad_max),tieBreakers.length>0].filter(Boolean).length
 const percent=Math.round(completion/6*100)
 return <div className="min-h-screen bg-[#f2f4f7] text-[#081f49]">
  <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-[72px] max-w-[1350px] items-center gap-4 px-4 sm:px-6"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-slate-400">Tournament Setup</p><p className="mt-1 font-black">{tournament.name}</p></div><div className="ml-auto flex gap-2"><Link href={`/organizations/${organizationId}/tournaments/${tournamentId}`} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600">← Workspace</Link></div></div></header>
  <main className="mx-auto max-w-[1350px] px-4 py-7 sm:px-6"><div className="grid gap-6 xl:grid-cols-[1fr_300px]">
   <div><div className="mb-6"><p className="text-xs font-bold text-[#0057ff]">{organization.name} / {sport??'Tournament'}</p><h1 className="mt-2 text-3xl font-black tracking-tight">Configure tournament</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Complete the tournament identity, schedule, registration controls, competition format, roster rules, scoring, disciplinary defaults and standings tie-breakers.</p></div>
   {query.saved==='1'&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-bold text-emerald-700">✓ Tournament setup saved successfully.</div>}{message&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-bold text-red-700">{message}</div>}
   <form action={updateTournamentSetupAction} className="space-y-6"><input type="hidden" name="organization_id" value={organizationId}/><input type="hidden" name="tournament_id" value={tournamentId}/>
    <section id="general" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">01 · General</p><h2 className="mt-2 text-xl font-black">Tournament information</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><label className={label}>Tournament name<input className={input} name="name" defaultValue={tournament.name} maxLength={160} required/></label><label className={label}>Season label<input className={input} name="season_label" defaultValue={tournament.season_label??''} placeholder="2026 Season"/></label><label className={`${label} md:col-span-2`}>Description<textarea className={`${input} min-h-28 resize-y`} name="description" defaultValue={tournament.description??''} placeholder="Describe this tournament"/></label><label className={label}>Timezone<input className={input} name="timezone" defaultValue={tournament.timezone||'Indian/Maldives'} required/></label><label className={label}>Visibility<select className={input} name="visibility" defaultValue={tournament.visibility}><option value="private">Private — members only</option><option value="unlisted">Unlisted — link access</option><option value="public">Public</option></select></label><label className={label}>Tournament status<select className={input} name="status" defaultValue={tournament.status}><option value="draft">Draft</option><option value="registration">Registration open</option><option value="scheduled">Scheduled</option><option value="live">Live</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="archived">Archived</option></select></label></div></section>
    <section id="schedule" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">02 · Schedule</p><h2 className="mt-2 text-xl font-black">Tournament & registration dates</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><label className={label}>Tournament starts<input className={input} type="date" name="start_date" defaultValue={tournament.start_date??''}/></label><label className={label}>Tournament ends<input className={input} type="date" name="end_date" defaultValue={tournament.end_date??''}/></label><label className={label}>Registration opens<input className={input} type="datetime-local" name="registration_opens_at" defaultValue={localDateTime(tournament.registration_opens_at)}/></label><label className={label}>Registration closes<input className={input} type="datetime-local" name="registration_closes_at" defaultValue={localDateTime(tournament.registration_closes_at)}/></label></div></section>
    <section id="registration" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">03 · Registration</p><h2 className="mt-2 text-xl font-black">Registration controls</h2><div className="mt-6 grid gap-3 md:grid-cols-2"><Toggle name="team_registration_enabled" title="Team registration" description="Allow teams to enter this tournament." checked={rules.team_registration_enabled??true}/><Toggle name="player_registration_enabled" title="Player registration" description="Allow player records to be registered to squads." checked={rules.player_registration_enabled??true}/><Toggle name="require_registration_approval" title="Require approval" description="New registrations must be approved before becoming active." checked={rules.require_registration_approval??true}/><Toggle name="allow_roster_changes" title="Allow roster changes" description="Permit squad edits until the roster lock time." checked={rules.allow_roster_changes??true}/></div><div className="mt-5"><label className={label}>Roster lock date & time<input className={input} type="datetime-local" name="roster_lock_at" defaultValue={rules.roster_lock_at??''}/></label></div></section>
    <section id="format" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">04 · Competition</p><h2 className="mt-2 text-xl font-black">Format & match rules</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><label className={label}>Competition format<select className={input} name="competition_format" defaultValue={rules.competition_format??'league'}><option value="league">League / round robin</option><option value="knockout">Knockout</option><option value="groups_knockout">Groups + knockout</option><option value="double_elimination">Double elimination</option><option value="custom">Custom</option></select></label><label className={label}>Match duration (minutes)<input className={input} type="number" min="1" name="match_duration_minutes" defaultValue={settings?.match_duration_minutes??''}/></label><label className={label}>Periods / halves<input className={input} type="number" min="1" name="period_count" defaultValue={settings?.period_count??''}/></label><label className={label}>Maximum substitutions<input className={input} type="number" min="0" name="substitutions_max" defaultValue={settings?.substitutions_max??''}/></label><label className={label}>Yellow cards for suspension<input className={input} type="number" min="0" name="yellow_card_suspension" defaultValue={rules.yellow_card_suspension??''}/></label><label className={label}>Red-card suspension (matches)<input className={input} type="number" min="0" name="red_card_suspension" defaultValue={rules.red_card_suspension??''}/></label></div><div className="mt-6 grid gap-3 md:grid-cols-3"><Toggle name="allow_draws" title="Allow draws" description="Matches may finish level when competition rules permit." checked={settings?.allow_draws??true}/><Toggle name="extra_time_enabled" title="Extra time" description="Enable extra time for matches requiring a winner." checked={settings?.extra_time_enabled??false}/><Toggle name="penalties_enabled" title="Penalty shootout" description="Enable penalties after tied knockout matches." checked={settings?.penalties_enabled??false}/></div></section>
    <section id="roster" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">05 · Rosters</p><h2 className="mt-2 text-xl font-black">Squad & lineup limits</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><label className={label}>Squad minimum<input className={input} type="number" min="0" name="squad_min" defaultValue={settings?.squad_min??''}/></label><label className={label}>Squad maximum<input className={input} type="number" min="1" name="squad_max" defaultValue={settings?.squad_max??''}/></label><label className={label}>Starting lineup minimum<input className={input} type="number" min="0" name="lineup_min" defaultValue={settings?.lineup_min??''}/></label><label className={label}>Starting lineup maximum<input className={input} type="number" min="1" name="lineup_max" defaultValue={settings?.lineup_max??''}/></label></div></section>
    <section id="standings" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">06 · Standings</p><h2 className="mt-2 text-xl font-black">Points & tie-breakers</h2><div className="mt-6 grid gap-5 md:grid-cols-3"><label className={label}>Win points<input className={input} type="number" min="0" step="0.001" name="points_for_win" defaultValue={settings?.points_for_win??3} required/></label><label className={label}>Draw points<input className={input} type="number" min="0" step="0.001" name="points_for_draw" defaultValue={settings?.points_for_draw??1} required/></label><label className={label}>Loss points<input className={input} type="number" min="0" step="0.001" name="points_for_loss" defaultValue={settings?.points_for_loss??0} required/></label></div><p className="mt-6 text-xs font-extrabold uppercase tracking-[0.08em] text-slate-500">Enabled tie-breakers</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['points','Points'],['head_to_head','Head-to-head'],['goal_difference','Goal difference'],['goals_for','Goals scored'],['wins','Wins'],['fair_play','Fair play']].map(([value,title])=><label key={value} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-bold"><input type="checkbox" name="tie_breakers" value={value} defaultChecked={tieBreakers.includes(value)} className="h-5 w-5 accent-[#0057ff]"/>{title}</label>)}</div><p className="mt-3 text-xs text-slate-400">These are stored as the tournament&apos;s standings tie-breaker configuration. Ordering can be expanded when the standings engine is built.</p></section>
    <section id="notes" className={card}><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#0057ff]">07 · Notes</p><h2 className="mt-2 text-xl font-black">Competition notes</h2><textarea className={`${input} min-h-32 resize-y`} name="competition_notes" defaultValue={rules.notes??''} placeholder="Internal setup notes, special competition rules, organizer instructions..."/></section>
    <div className="sticky bottom-4 z-10 flex flex-col-reverse gap-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-xl backdrop-blur sm:flex-row sm:justify-end"><Link href={`/organizations/${organizationId}/tournaments/${tournamentId}`} className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-200 bg-white px-6 text-sm font-bold text-slate-600">Cancel</Link><button type="submit" className="min-h-12 rounded-xl bg-[#0057ff] px-7 text-sm font-extrabold text-white shadow-lg shadow-blue-200 hover:bg-[#0047d8]">Save all tournament settings</button></div>
   </form></div>
   <aside className="hidden xl:block"><div className="sticky top-24 space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.1em] text-[#0057ff]">Setup progress</p><div className="mt-3 flex items-end justify-between"><span className="text-3xl font-black">{percent}%</span><span className="text-xs font-bold text-slate-400">{completion}/6 essentials</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#0057ff]" style={{width:`${percent}%`}}/></div></section><nav className="rounded-2xl border border-slate-200 bg-white p-3">{[['general','General information'],['schedule','Dates & schedule'],['registration','Registration'],['format','Competition rules'],['roster','Squad & lineup'],['standings','Standings'],['notes','Notes']].map(([id,title])=><a key={id} href={`#${id}`} className="block rounded-xl px-4 py-3 text-sm font-bold text-slate-600 hover:bg-blue-50 hover:text-[#0057ff]">{title}</a>)}</nav><div className="rounded-2xl bg-[#081f49] p-5 text-white"><p className="text-xs font-extrabold">Current status</p><p className="mt-2 text-xl font-black capitalize">{tournament.status}</p><p className="mt-2 text-xs leading-5 text-white/60">Changes are protected by organization membership and Supabase RLS.</p></div></div></aside>
  </div></main>
 </div>
}